[build]
  command = "node generate_gpt_readme.js"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/gpt4-turbo"
  to = "/.netlify/functions/gpt4-turbo"
  status = 200

[[redirects]]
  from = "/api/vector-search"
  to = "/.netlify/functions/vector-search"
  status = 200
